name: Attatch Zip to Pull Request
on: push

jobs:
  plugin_machine_builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imaginarymachines/plugin-machine-builder@main
        with:
          token: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          path: ${{ github.workspace }}
