name: Attatch Zip to Pull Request
on: push

jobs:

  plugin_machine:
    runs-on: ubuntu-latest
    steps:
      - uses: imaginarymachines/plugin-machine-builder@0.1.5
        with:
          token: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
