name: Attatch Zip to Pull Request
on: push

jobs:

  plugin-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # Build plugin for prod, zip and upload
      - name: Zip
        id: pluginmachine
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npm i plugin-machine -g
          plugin-machine plugin build --buildDir=output --pluginDir="${{ github.workspace }}" --token="${{ secrets.PLUGIN_MACHINE_TOKEN }}"
          plugin-machine plugin zip --buildDir=output --pluginDir="${{ github.workspace }}" --token="${{ secrets.PLUGIN_MACHINE_TOKEN }}"
          OUTPUT=`plugin-machine upload --fileName=jpd2.zip --quiet --token="${{ secrets.PLUGIN_MACHINE_TOKEN }}"`
          echo "::set-output name=url::$OUTPUT"
      # Get PR number and then comment on it
      - uses: jwalton/gh-find-current-pr@v1
        id: finder
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.finder.outputs.pr }}
          message: |
            SHA ${{ github.sha }}
            LINK: ${{steps.pluginmachine.outputs.url}}
