name: Attatch Zip to Pull Request
on: push

jobs:

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: imaginarymachines/plugin-machine-builder@main
        with:
          token: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          path: ${{ github.workspace }}
