name: Attatch Zip to Pull Request
on: push

jobs:

  plugin-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Zip
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npm i plugin-machine -g
          plugin-machine plugin build --buildDir=output --pluginDir="${{ github.workspace }}" --token="${{ secrets.PLUGIN_MACHINE_TOKEN }}"
          plugin-machine plugin zip --buildDir=output --pluginDir="${{ github.workspace }}" --token="${{ secrets.PLUGIN_MACHINE_TOKEN }}"
          ls
          plugin-machine upload --fileName=jpd2.zip --token="$env:PLUGIN_MACHINE_TOKEN"
