name: Attatch Zip to Pull Request
on: pull_request

jobs:

  plugin_machine:
    runs-on: ubuntu-latest
    steps:
      - uses: imaginarymachines/plugin-machine-builder@latest
        with:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
