name: Attatch Zip to Pull Request
on: push

jobs:

  plugin-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Zip
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npm i plugin-machine -g
          plugin-machine plugin build --buildDir=output --pluginDir="${{ github.workspace }}" --token="$env:PLUGIN_MACHINE_TOKEN"
          plugin-machine plugin zip --buildDir=output --pluginDir="${{ github.workspace }}" --token="$env:PLUGIN_MACHINE_TOKEN"

      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: jpd2.zip
          path: ${{ github.workspace }}/jpd2.zip

      - uses: actions/github-script@v6
        with:
          script: |
            let artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            if( 0 < artifacts.data.total_count ){
              let artifact = artifacts.data[0];
              await github.rest.issues.createComment({
                issue_number: 1,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `[${artifact.name}](${artifact.archive_download_url}`)
              })
            }
