name: Attatch Zip to Pull Request
on: pull_request

jobs:

  plugin_machine:
    runs-on: ubuntu-latest
    steps: 
      - uses: imaginarymachines/plugin-machine-builder@latest
        with:
          milliseconds: 1000
