name: Attatch Zip to Pull Request
on: push

jobs:

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: imaginarymachines/plugin-machine-builder@0.1.5
        with:
          token: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Zip
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npm i plugin-machine -g
          plugin-machine plugin build --buildDir=output --pluginDir="${{ github.workspace }}" --token="$env:PLUGIN_MACHINE_TOKEN"
          plugin-machine plugin zip --buildDir=output --pluginDir="${{ github.workspace }}" --token="$env:PLUGIN_MACHINE_TOKEN"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{ github.workspace }}/output
      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: zip
          path: ${{ github.workspace }}/jpd2.zip
